Output docs/demo.gif

Set WindowBar Colorful
Set Theme AdventureTime
Set PlaybackSpeed 1
Set FontSize 18
Set FontFamily "Hack"
Set Height 400
Set TypingSpeed 50ms

Type "Ahoy, fellow sailor! Let's reel in some repos."
Sleep 3s
Set TypingSpeed 1ms
Backspace 49

Ctrl+L

Set TypingSpeed 50ms
Enter 1
Type "piscator reel azemetre"
Sleep 2s
Enter
Sleep 5s
Enter 2
Type "wow, what a haul!"
Sleep 5s

# Cleanup
Hide
Backspace 17
Type "rm -rf azemetre"
Enter
