name: "Run tests, vet, staticchecker, and coverage"

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
      - release

env:
  GO111MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -cover ./...

      - name: Collect Test Coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Generate coverage report
        run: go tool cover -func=coverage.out > coverage.txt

      - name: Print coverage report
        run: cat coverage.txt

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.coverage.outputs.report }}
            ```
          edit-mode: replace
